### ISSUE TITLE
Hook UI

### ISSUE THREAD

**Issue by Edou24** [Infixo/CS2-InfoLoom#10]
you need to change the mod to be able to work with the new hook ui

**Comment by Infixo** [comment]
The mod WORKS with new HookUI, I am using it with v0.3.9.
However, you may install it manually from Thunderstore because there is still an old reference which cannot be changed without uploading a new version of the mod.

**Comment by Infixo** [comment]
Ok, I've changed it. Please check now.

**Comment by Edou24** [comment]
all good thanks
