### ISSUE TITLE
PDX

### ISSUE THREAD

**Issue by mi3key** [Infixo/CS2-InfoLoom#18]
Hello,
I dont really have any issue with your mod, but I didnt know how to reach you out beside on here.
are you planning on releasing this mod on PDX anytime soon? if so do you have an ETA for the release?
this is one of the mods I use the most! I really love it. I am missing it since I transitioned into PDX from TS and I am afraid to run both together

**Comment by Infixo** [comment]
Hi :) yes, I am migrating InfoLoom to pdx too. I am finishing migrating Economy Rebalance and did some progress with InfoLoom. I plan to have it on Pdx this week. So, keep and your fingers crossed and wish me luck 😀

**Comment by Alph4d0g** [comment]
Good Luck! Love InfoLoom btw <3

**Comment by Infixo** [comment]
The mod is now on PDXMods 😁

**Comment by mi3key** [comment]
> The mod is now on PDXMods 😁

appreciate your efforts mate. I actually got to download it from your profile before you published it :)
