### ISSUE TITLE
Add Uneducated to Demographics - Feature Request

### ISSUE THREAD

**Issue by ghost** [Infixo/CS2-InfoLoom#4]
Hello,

If possible, please add uneducated to Demographics. Being able to see uneducated would help with tuning Population Rebalance.

Thank you!
-Rob

**Comment by Infixo** [comment]
Can you please elaborate? Demographics window doesn't show education levels at all.
The education levels for the entire population are a standard feature, in Education infoview. What would be point in duplicating that?

**Comment by Infixo** [comment]
Closed due to lack of response.
