### ISSUE TITLE
[Bug] The total number of labor force in the labor force structure panel is greater than the total population displayed in the game

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [Infixo/CS2-InfoLoom#5]
Game Version: 1.0.18f1
Mod Version: 0.7.0

**Comment by Infixo** [comment]
Too little info to work with. What do you mean by "labor force", are you talking about workforce or workplaces? Can you post screenshot of this data? What is the difference vs. population?

**Comment by GIS-PuppetMaster** [comment]
> Too little info to work with. What do you mean by "labor force", are you talking about workforce or workplaces? Can you post screenshot of this data? What is the difference vs. population?信息太少，无法使用。您所说的“劳动力”是什么意思，您指的是劳动力还是工作场所？您可以发布此数据的屏幕截图吗？与人口相比有何差异？

I mean the number of workers. Someone from discord just told me that the worker number shown in this mod includes the commuters from outside my town, so maybe it's not a bug. If so, please close this issue.

**Comment by Infixo** [comment]
Yes, this is true. Commuters are people not from your city that work in your city. So, it is entirely possible to have more workers than population. That is one of the reasons why I've added info about commuters. High number of commuters may also cause high unemployment, despite having enough workplaces - they are taken by non-citizens.

**Comment by GIS-PuppetMaster** [comment]
> Yes, this is true. Commuters are people not from your city that work in your city. So, it is entirely possible to have more workers than population. That is one of the reasons why I've added info about commuters. High number of commuters may also cause high unemployment, despite having enough workplaces - they are taken by non-citizens.

Thanks for the explanation. This is the problem I had before, totally broke my game, 43% of citizens don't have jobs, and the worker number shown in this mod is 28w, but I population just reduced from 27w to 17w, also the birth ratio is low. That's why I thought maybe it's a display bug of this mod.
